# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 929f898852d26cb55bb660c1abb9a3902639f3016766a18a8f7e3ea58222d4dfdd5b4aa2504c39da153363441cb7c35956e9f5b28e8e1ed004e9e01bdc67f397

test:
  secret_key_base: dee77ef151761aabaedd563c27bd14da16cfb7377fb2285a0f4c952516799bc434734a8d63ee69ba6d5c74341b5ec659496ccbd32ebcdce92cf67196b273b527

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
